### ISSUE TITLE
markdown后端接口设计

### ISSUE THREAD

**Issue by zbzbw** [whatahardchoice/PhyLab#36]
包括以下内容：
1. api方面，是在原有api基础上修改还是另开新的api？
2. http请求设计，包括请求的类型、字段等
3. 后端控制器（controller）设计，包括输入和返回的内容
4. 脚本设计，即脚本是否需要更改，脚本更改的大致方案

成果要求：
将以上内容归纳后回复在issue下。

请在issue下回复成果后再关闭issue。

**Comment by RookieFanzk** [comment]
#### 1.api方面，是在原有api基础上修改还是另开新的api？
选择在原api基础上修改。
更改\PhyLab\Phylab\public\js\reportCore.js文件中，$('#button-generate-report').click(function ())函数。
更改\PhyLab\Phylab\app\Http\Controllers\ReportController.php文件中，create()函数。

#### 2.http请求设计，包括请求的类型、字段等
发送POST请求，提交用户所填的数据。

#### 3.后端控制器（controller）设计，包括输入和返回的内容
post 传入 xml 模板文件
```
	$data = ["status"=> "",
             "experimentId" => "",
             "link"  => "",
             "message" => "",
             "errorLog"=>array()];
```
然后调用python脚本处理数据，返回字符串后填入markdown文件，然后调用python脚本转换为html文件，即最终返回一个页面。

#### 4.脚本设计，即脚本是否需要更改，脚本更改的大致方案
在每个小实验的数据处理脚本不需要做改变，只需要在总入口脚本中，将返回的字符串填入markdown而非tex文件，增加md转html功能即可。
