### ISSUE TITLE
markdown前端接口设计

### ISSUE THREAD

**Issue by zbzbw** [whatahardchoice/PhyLab#37]
包括以下内容：
1. 前端界面需要新增哪些内容来让用户选择markdown或latex？包括但不限于新的按钮、选择框等。
2. 前端如何分别显示latex或markdown模板返回的结果？
3. javascript需要如何修改？提供大致思路。

成果要求：
对于1/2 最好能提供相应的设计草图。
对于3 提供大致的编码思路。

请在issue下回复成果后再关闭issue。

**Comment by RookieFanzk** [comment]
#### 1.前端界面需要新增哪些内容来让用户选择markdown或latex？包括但不限于新的按钮、选择框等。
打算是在用户点击生成数据报告按钮时给出一个弹窗，其中有两个选择项。大体如下：
选择生成数据报告的方式：
· Letax(可收藏、下载的PDF)  · Markdown(在线预览的html页面)

#### 2.前端如何分别显示latex或markdown模板返回的结果？
原latex生成的PDF嵌入在一个显示框内，打算将markdown转化得到的html页面也在该显示框中显示。

#### 3.javascript需要如何修改？提供大致思路。
更改\PhyLab\Phylab\public\js\reportCore.js文件中，$('#button-generate-report').click(function ())函数。
点击会给出一个弹窗，供用户选择。得到一个返回值。
更改\PhyLab\Phylab\app\Http\Controllers\ReportController.php文件中，create()函数，增加一个参数，即该返回值，来控制生成报告的脚本。
