### ISSUE TITLE
markdown后端处理脚本

### ISSUE THREAD

**Issue by zbzbw** [whatahardchoice/PhyLab#39]
类似latex的处理脚本，主要工作是调用计算脚本并将结果生成至.md文件中，若为后端模板生成则同时需要编译.md文件生成html代码。

成果要求：
对应commit。

请在issue下提供主要commit截图后再关闭issue。

**Comment by RookieFanzk** [comment]
![](https://raw.githubusercontent.com/RookieFanzk/link/master/commit1.png)
