### ISSUE TITLE
markdown前端用户选择界面

### ISSUE THREAD

**Issue by zbzbw** [whatahardchoice/PhyLab#40]
主要包括让用户选择如何生成报告（latex还是markdown）的界面部分。包括html及js。
特别注意需要考虑实验对latex和markdown的支持，不支持者不让选。

成果要求：
对应commit。

请在issue下提供主要commit截图后再关闭issue。

**Comment by RookieFanzk** [comment]
![](https://raw.githubusercontent.com/RookieFanzk/link/master/commit5.png)
