### ISSUE TITLE
markdown前端报告展示界面

### ISSUE THREAD

**Issue by zbzbw** [whatahardchoice/PhyLab#41]
成果要求：
对应commit。

请在issue下提供主要commit截图后再关闭issue。

**Comment by RookieFanzk** [comment]
![](https://raw.githubusercontent.com/RookieFanzk/link/master/commit3.png)

**Comment by RookieFanzk** [comment]
![](https://raw.githubusercontent.com/RookieFanzk/link/master/commit4.png)
