### ISSUE TITLE
2200116 实验模板

### ISSUE THREAD

**Issue by zbzbw** [whatahardchoice/PhyLab#60]
tex和markdown
成果要求：
对应commit。

请在issue下提供主要commit截图后再关闭issue。

**Comment by kenyin123** [comment]
https://github.com/whatahardchoice/PhyLab/commit/1b5cf08e639c3931836d1465b15d3228a0b3f87c
tex完成

**Comment by Hefarry** [comment]
![1](https://user-images.githubusercontent.com/48465622/57596711-b2f15400-757e-11e9-873a-6d0916a16c74.png)
![2](https://user-images.githubusercontent.com/48465622/57596714-b8e73500-757e-11e9-95ec-b78085edf7c4.png)
