### ISSUE TITLE
其余设计性实验html

### ISSUE THREAD

**Issue by zbzbw** [whatahardchoice/PhyLab#67]
D04及G01~G04部分

成果要求：
commit截图。

**Comment by kenyin123** [comment]
https://github.com/whatahardchoice/PhyLab/commit/b011f35417a1dd9c96eb73476c298dd166331c30
https://github.com/whatahardchoice/PhyLab/commit/065e18f9639a129092d1dec05d2c49bface63c28

**Comment by kenyin123** [comment]
[G04]https://github.com/whatahardchoice/PhyLab/commit/17d6970f5fa012850904f8b7800daae6c712015e

**Comment by Hefarry** [comment]
![1](https://user-images.githubusercontent.com/48465622/57970550-09aec180-79b5-11e9-8dd0-c3658077122a.png)
![2](https://user-images.githubusercontent.com/48465622/57970553-10d5cf80-79b5-11e9-8320-3d32d58ed8a0.png)
![3](https://user-images.githubusercontent.com/48465622/57970554-1a5f3780-79b5-11e9-95d0-18838a7ee4d5.png)
